"""Promoted surface for MIPRO-style optimization in synth-lab.

Import path:
``from synth_optimizers.miprov2.core import DiscreteMiproOptimizer``.

This facade now includes:
- async discrete TPE primitives
- MIPRO trial/state dataclasses
- a thin discrete optimizer with suggest/observe/run_batch loop
- Phase-1 typed program schema + search-space compiler helpers
- Phase-2 async rollout runner + candidate-native evaluator contract
- Phase-3 OpenEnv ReAct-style proposer lane helpers
"""

from __future__ import annotations

from synth_optimizers.miprov2.async_discrete_tpe import (
    NONE_TRANSFORM,
    AsyncDiscreteTpeOptimizer,
    TpeConfig,
    TpeObservation,
)
from synth_optimizers.miprov2.core.optimizer import (
    DiscreteMiproOptimizer,
    EvaluateCandidate,
    EvaluateOutcome,
    MiproObservationSummary,
    MiproOptimizer,
    MiproSearchState,
    MiproTrialResult,
    ScoreWithDetails,
    canonicalize_lever_bundle,
    lever_bundle_hash,
)
from synth_optimizers.miprov2.core.contracts import (
    MiproCandidateExecutionMode,
    MiproCandidateRecord,
    MiproCompatResult,
    MiproCompatRunConfig,
    MiproComponentSpec,
    MiproEvaluationBatch,
    MiproExecutionContract,
    MiproModelTransformRecord,
    MiproRunEvent,
    MiproRuntimeBinding,
    MiproSftConfig,
)
from synth_optimizers.miprov2.core.checkpointing import (
    CHECKPOINT_STAGE_BEFORE_PROPOSER,
    compiled_space_from_snapshot,
    compiled_space_to_snapshot,
    export_candidate_train_scores_from_ledger,
    load_proposer_checkpoint,
    proposed_candidates_from_outcome,
    proposer_context_from_dict,
    proposer_context_to_dict,
    proposer_replay_summary,
    run_proposer_from_checkpoint,
    trial_from_dict,
    trial_to_dict,
    write_proposer_checkpoint,
)
from synth_optimizers.miprov2.core.phase2_runner import (
    EvaluateCandidateFn,
    EvaluateCandidateOutcome,
    EvaluateCandidateWithDetails,
    MiproHeldoutSnapshot,
    MiproPhase2Config,
    MiproPhase2Outcome,
    build_baseline_config,
    run_train_loop,
)
from synth_optimizers.miprov2.core.phase3_runner import (
    MiproGroundingHooks,
    MiproGroundingHooksLike,
    MiproPhase3Config,
    MiproPhase3Outcome,
    MiproProposerStepInput,
    EvaluateQueuedRolloutFn,
    SampleTrainRowsFn,
    SampleTrainRowsOutcome,
    SummarizeRecentTrialsFn,
    SummarizeRecentTrialsOutcome,
    run_phase3_loop,
)
from synth_optimizers.miprov2.core.proposer_environment import (
    MiproProposerEnvironment,
    tool_state_from_dict,
    tool_state_to_dict,
)
from synth_optimizers.miprov2.core.proposer_memory import (
    MiproBet,
    MiproBetResolution,
    MiproBetStatus,
    MiproHypothesis,
    MiproHypothesisAdjustment,
    MiproHypothesisStatus,
    bet_id_for,
    empty_memory_state,
    hypothesis_adjustment_id_for,
    hypothesis_id_for,
    normalize_memory_state,
    proposer_memory_summary,
)
from synth_optimizers.miprov2.core.proposer_sessions import (
    MiproProposerEvent,
    MiproProposerSession,
    MiproProposerSessionStore,
)
from synth_optimizers.miprov2.core.proposer_tools import (
    MiproProposerToolResult,
    MiproProposerToolState,
    annotate_mipro_tool,
    execute_mipro_tool,
)
from synth_optimizers.miprov2.core.program_compiler import (
    CompiledMiproSpace,
    compile_search_space,
    decode_config,
    demo_component_key,
    instruction_component_key,
    list_registered_instruction_transforms,
    query_instruction_transform_compatibility,
    register_instruction_candidate,
    register_instruction_transform,
)
from synth_optimizers.miprov2.core.instruction_transforms import (
    InstructionTransform,
    InstructionTransformError,
    compile_instruction_text,
)
from synth_optimizers.miprov2.core.program_model import (
    DemoMessage,
    DemoSlotTemplate,
    MiproDemo,
    MiproModuleTemplate,
    MiproProgramCandidate,
    MiproProgramTemplate,
    StaticFewShotDemo,
    TrajectorySnippetDemo,
    demo_from_dict,
    materialized_lever_bundle_hash,
    materialized_lever_bundle_payload,
)
from synth_optimizers.miprov2.core.proposer_openenv import (
    GeminiOpenEnvReactAgent,
    GroqOpenEnvReactAgent,
    HeuristicOpenEnvReactAgent,
    MiproDemoPatch,
    MiproInstructionPatch,
    MiproOpenEnvAction,
    MiproOpenEnvProposerConfig,
    MiproOpenEnvProposerContext,
    MiproOpenEnvProposerOutcome,
    MiproOpenEnvProposerVariant,
    MiproOpenEnvReactAgent,
    OpenAIOpenEnvReactAgent,
    apply_instruction_transforms,
    build_openenv_tool_catalog,
    clone_compiled_space,
    proposer_outcome_summary,
    run_openenv_react_proposer,
    summarize_compiled_space,
    sync_optimizer_search_space,
)
from synth_optimizers.miprov2.core.run_ledger import (
    LedgerHeldoutSnapshot,
    LedgerObservation,
    LedgerProposerRound,
    MiproRunResumeState,
    RunLedgerHeldoutSnapshot,
    SQLiteMiproRunLedger,
    load_resume_state,
    open_sqlite_run_ledger,
)
from synth_optimizers.miprov2.core.rollout_queue import (
    MiproCandidateInterventionRef,
    MiproQueuedRollout,
    MiproQueuedRolloutResult,
    MiproRolloutQueue,
    MiproRolloutQueueCommit,
    MiproRolloutQueueOverride,
    queue_id_for,
    rollout_id_for,
)

__all__ = [
    "NONE_TRANSFORM",
    "AsyncDiscreteTpeOptimizer",
    "TpeConfig",
    "TpeObservation",
    "MiproOptimizer",
    "MiproTrialResult",
    "MiproSearchState",
    "MiproObservationSummary",
    "DiscreteMiproOptimizer",
    "EvaluateCandidate",
    "EvaluateOutcome",
    "ScoreWithDetails",
    "canonicalize_lever_bundle",
    "lever_bundle_hash",
    "MiproCandidateExecutionMode",
    "MiproCandidateRecord",
    "MiproCompatResult",
    "MiproCompatRunConfig",
    "MiproComponentSpec",
    "MiproEvaluationBatch",
    "MiproExecutionContract",
    "MiproModelTransformRecord",
    "MiproRunEvent",
    "MiproRuntimeBinding",
    "MiproSftConfig",
    "CHECKPOINT_STAGE_BEFORE_PROPOSER",
    "compiled_space_from_snapshot",
    "compiled_space_to_snapshot",
    "export_candidate_train_scores_from_ledger",
    "load_proposer_checkpoint",
    "proposed_candidates_from_outcome",
    "proposer_context_from_dict",
    "proposer_context_to_dict",
    "proposer_replay_summary",
    "run_proposer_from_checkpoint",
    "trial_from_dict",
    "trial_to_dict",
    "write_proposer_checkpoint",
    "EvaluateCandidateFn",
    "EvaluateCandidateOutcome",
    "EvaluateCandidateWithDetails",
    "EvaluateQueuedRolloutFn",
    "MiproHeldoutSnapshot",
    "MiproPhase2Config",
    "MiproPhase2Outcome",
    "build_baseline_config",
    "run_train_loop",
    "SampleTrainRowsOutcome",
    "SampleTrainRowsFn",
    "SummarizeRecentTrialsOutcome",
    "SummarizeRecentTrialsFn",
    "MiproGroundingHooksLike",
    "MiproGroundingHooks",
    "MiproPhase3Config",
    "MiproPhase3Outcome",
    "MiproProposerStepInput",
    "run_phase3_loop",
    "MiproProposerEnvironment",
    "MiproHypothesis",
    "MiproHypothesisAdjustment",
    "MiproBet",
    "MiproHypothesisStatus",
    "MiproBetStatus",
    "MiproBetResolution",
    "hypothesis_id_for",
    "hypothesis_adjustment_id_for",
    "bet_id_for",
    "empty_memory_state",
    "normalize_memory_state",
    "proposer_memory_summary",
    "MiproProposerEvent",
    "MiproProposerSession",
    "MiproProposerSessionStore",
    "MiproProposerToolResult",
    "MiproProposerToolState",
    "annotate_mipro_tool",
    "execute_mipro_tool",
    "tool_state_from_dict",
    "tool_state_to_dict",
    "MiproOpenEnvAction",
    "MiproOpenEnvReactAgent",
    "MiproOpenEnvProposerContext",
    "MiproOpenEnvProposerConfig",
    "MiproOpenEnvProposerVariant",
    "MiproInstructionPatch",
    "MiproDemoPatch",
    "MiproOpenEnvProposerOutcome",
    "GeminiOpenEnvReactAgent",
    "GroqOpenEnvReactAgent",
    "OpenAIOpenEnvReactAgent",
    "HeuristicOpenEnvReactAgent",
    "apply_instruction_transforms",
    "build_openenv_tool_catalog",
    "clone_compiled_space",
    "summarize_compiled_space",
    "run_openenv_react_proposer",
    "sync_optimizer_search_space",
    "proposer_outcome_summary",
    "LedgerObservation",
    "RunLedgerHeldoutSnapshot",
    "LedgerHeldoutSnapshot",
    "LedgerProposerRound",
    "MiproRunResumeState",
    "SQLiteMiproRunLedger",
    "open_sqlite_run_ledger",
    "load_resume_state",
    "MiproCandidateInterventionRef",
    "MiproQueuedRollout",
    "MiproQueuedRolloutResult",
    "MiproRolloutQueue",
    "MiproRolloutQueueCommit",
    "MiproRolloutQueueOverride",
    "queue_id_for",
    "rollout_id_for",
    "DemoMessage",
    "StaticFewShotDemo",
    "TrajectorySnippetDemo",
    "MiproDemo",
    "demo_from_dict",
    "DemoSlotTemplate",
    "MiproModuleTemplate",
    "MiproProgramTemplate",
    "MiproProgramCandidate",
    "materialized_lever_bundle_payload",
    "materialized_lever_bundle_hash",
    "InstructionTransform",
    "InstructionTransformError",
    "compile_instruction_text",
    "CompiledMiproSpace",
    "compile_search_space",
    "decode_config",
    "instruction_component_key",
    "demo_component_key",
    "register_instruction_candidate",
    "register_instruction_transform",
    "list_registered_instruction_transforms",
    "query_instruction_transform_compatibility",
]
