"""Public Synth optimizer package.

The HTTP service (`gepa_serve`) is the public surface. Raw worker/workspace
PyO3 exports were demoted in the v2 service rebuild and are no longer importable.
"""

from ._synth_optimizers import (
    BudgetExceededError,
    CacheCorruptError,
    CacheFullError,
    CacheMissError,
    CancelledError,
    ConfigError,
    ContainerContractError,
    EventCompareError,
    GepaRun,
    GepaRunResult,
    InvariantError,
    OptimizerDiskBudgetError,
    OptimizerHttpError,
    OptimizerIoError,
    OptimizerJsonError,
    OptimizerSqliteError,
    OptimizerTomlDecodeError,
    ProposerError,
    RunFailedError,
    StateTransitionError,
    SynthOptimizerError,
    __version__,
    events_compare,
    events_replay,
    gepa_serve,
)

__all__ = [
    "BudgetExceededError",
    "CacheCorruptError",
    "CacheFullError",
    "CacheMissError",
    "CancelledError",
    "ConfigError",
    "ContainerContractError",
    "EventCompareError",
    "GepaRun",
    "GepaRunResult",
    "InvariantError",
    "OptimizerDiskBudgetError",
    "OptimizerHttpError",
    "OptimizerIoError",
    "OptimizerJsonError",
    "OptimizerSqliteError",
    "OptimizerTomlDecodeError",
    "ProposerError",
    "RunFailedError",
    "StateTransitionError",
    "SynthOptimizerError",
    "__version__",
    "events_compare",
    "events_replay",
    "gepa_serve",
]
